### ISSUE TITLE
Cannot find module tokens.json

### ISSUE THREAD

**Issue by shyim** [kettui/web-discordjs-bot#11]
Hello,

i am trying to install the bot, but i get the message that he cant find the tokens.json.
I cant found a tokens.json also in the Repository. Must i create it?

Message
`Error: Cannot find module './config/tokens.json'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/web-discordjs-bot/src/server/bot.js:3:1)
    at Module._compile (module.js:541:32)
    at loader (/root/web-discordjs-bot/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/root/web-discordjs-bot/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)`

I used following commad: PORT=9000 node entry.js
I also installed rethinkdb and started it

Nice Project :)

**Comment by kettui** [comment]
Oh, I didn't expect anyone to actually stumble across this project so I haven't taken that into account (hence the "meant for personal use as of now" in the description). Nice to see that you managed to find it though, and thanks for the compliment!  

But yes, the tokens.json file should indeed be created (and updated with personal tokens for different APIs). Currently My tokens.json contains the following keys:
```js
{
    "discord": {
        "token": "Discord bot token"
    },
    "twitch": {
        "clientId": "Twitch client ID for API calls",
        "follower": {
            "name": "Name of the Twitch account used for following channels",
            "token": "OAuth token from the account used for following channels (used for actions that require it, such as following Twitch channels etc.)"
        }
    },
    "youtube": {
        "apiKey": "YouTube API key (created/obtained from https://console.developers.google.com/apis/credentials)"
    },
    "openweather": {
        "apiKey": "OpenWeatherMap API key"
    }
}
```
The last API key (openweather) is used for the latest (and undocumented) feature of the project, which basically checks through [hard-coded locations](https://github.com/kettui/web-discordjs-bot/blob/master/src/server/models/weather/WeatherChecker.js#L9) and displays their weather information in the bot's playing status in Discord.  

I had originally planned to streamline the setup process (once the project got to a point that I was ready to make it fully public), but as it's still a work in progress, this part is kind of a pain in the ass if one does not already have these API keys generated beforehand.

**Comment by kettui** [comment]
Oh and in addition (if the token hassle didn't already kill your interest), the web client has an authentication system but there's no register forms in place as of now, so the easiest way to add a user is to call [this](https://github.com/kettui/web-discordjs-bot/blob/master/src/client/services/feathers/index.js#L14) function manually.  

Another thing I realized as I looked that one up, is the socket.io endpoint specified above (line 8), which can simply be set to io('/'), regardless of the environment (the current setting wouldn't work for you if you want to use port 9000)

**Comment by shyim** [comment]
Okay. Now it looks so i have problems to connecting to the rethinkdb. I will look later. never used rethinkdb before :)

**Comment by kettui** [comment]
The app expects there to be a database called "discordjs", so if you create it via the RethinkDB admin dashboard (a web client - it runs on port 8080 by default), there should be no further problems with that.
